creation_rules:
  - pgp: "B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98"
    encrypted_regex: ^(.+)$
    paths:
      - "*.env"
      - "*.json"
  - pgp: "B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98"
    encrypted_regex: ^(data|stringData)$
    paths:
      - "*.yaml"