server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:ANrufeCiFc5gLkoBGRomZ8xcaA==,iv:febqLiLIWr8uL31t9DAzugqxX7Dh7RIaB8I/hXi/m/Y=,tag:zzJOlkDnlM4kSH8r4UgFgA==,type:str]
        key-store-password: ENC[AES256_GCM,data:XqFph2p71MhZJ9Y=,iv:gBL2IuCiCZ8mqYZsfsd10VdX5vaxB7cqWvH+RCQz2PE=,tag:4qjg5t8ewKG1oLYM4nIubA==,type:str]
        key-store-type: ENC[AES256_GCM,data:PsDliJDd,iv:jZZPGn41EuCCUsZcdbJjdnBlTwNjG0h3bh0YsDBG9xA=,tag:Xk0e1E973yTE2lHtQzolyw==,type:str]
        key-alias: ENC[AES256_GCM,data:MD1S6tA/uAQVlw==,iv:mpT1GJZsNazBZ91dQCQDMuneVD4dwAak0W4YK9jGh80=,tag:tBhDn3xk8E3SIPT/ug2raA==,type:str]
spring:
    jpa:
        hibernate:
            ddl-auto: create
app:
    domain:
        frontend: ENC[AES256_GCM,data:lgsFHHbsnVFADHvJbJNM5+06BdrYtLorEwuJ,iv:FbGwHvsL5CTZylsy2K/+K7M43kGHBV/l0Eas1LJD9Hw=,tag:/ieKZs5K5yk7nTPtk3L76Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-18T14:47:03Z"
    mac: ENC[AES256_GCM,data:bxHntyR51wxTVCA7ZfSTZ3I9AWLV3g7gt51y30vj8YMq1DzqZRCOP3PI6AZ3OSHLM5dsNzqzDBfLJ/ot28GZ+wUdHZ+h04plhCm+DwVzixX4BY+AUFPQebZ6fkSszxXlS72yAHOu/WxQbVlSrPgNMcrizhmqt38OfC0fcHy9vIo=,iv:C9bnrQebhi8WiYnctKB8bOGGiSapIxM1yXK8c087g7g=,tag:6RGUFRScGOQfodchIRO1zA==,type:str]
    pgp:
        - created_at: "2025-04-18T14:47:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/9HyP0UeDAfr0t1E4TknjdLfeWHlIAIA+/1B2zoMWdN+6D
            SUdN6OLvYhDjKvvn5oWv9FKAFVjK9ArtCp5LbNyws8n/1XmDMhZBU2JfMk4+omC0
            meSy0p20bUmhfvEkFYCnCjY/yD8MGzyglTBiq1ABwWaWXj7vlFNl6q1oVwEe0FO3
            nyJBpGBjIeXXCmlGHcmFVmNIO+tjvXLneA/0Hdzb3tahaG5vUmZp+LwPHYql48X1
            CQxhTJ3yZBh8kKtT1XM36lhBbr8Zg9T0zANWgrEJzjA6M5XNh84cojP+m14yn08L
            J39cD00huJr4hUs0G2FtBx/vaiRcHKA/IQrvNdmJrxDgd7oyYZfFEEGMW7nQYLOy
            KidbbfqhW4zRokLVcq8Rzv0ZnXRyTF5G8CcHLAxXC57Xdw+gnoQRRTVLhNqsZXtv
            SuGkQ3exBK9LFj32jEsXeweTQAZc854HmEoKCYvU4Jd7ls6pgitCUDhJfskmxIvE
            ysYVxmWDXv4phLZWPNIvVRL0WlwnmLzh7/cCsEV12D/BuIwBqau8zPHgTvIqiLQJ
            JKExYNzK8JWJD7KIetAf/fsjfB/gZWB05ch6KGUhOm0J4VST7Sq0upOmdNsMn6Iq
            sS+3favWmT4XQVBJmEpayWHy8IVYdGQ+aWILlJqjtW6bMyBTPe66uZ17F4ArQ+fS
            XgEnN37ad5AZc3OxDY5hXhFy+r+UQZ7b/q4r30T6TQTMPKQKw4JOz+OOvRHazKpF
            8ckVLk6OXmprazAqa8ITZ0XleTqKskSNcXJUrLUvt1+BtPYM5Eg+d5VA2Gr9R1Q=
            =cE0N
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|username|host|domain).*)$
    version: 3.9.3
