spring:
    profiles:
        active: local
jwt:
    secret: ENC[AES256_GCM,data:Qv3uA3fwWhbFiOtBk+EjEw4whwdi3Iw9UOBUFAESZeO8DB5rVTJ0WZw4oLQ=,iv:W83iTnPvFn5i+FLWB3RkfWDY59Ec9bVVdYj7kd5/mDo=,tag:5fAO7QywpsylQFfskjxuQg==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:qckm,iv:gXeAMSpM9De50FBhltA+tOOB5M0vytUiJt7VBHSMfgU=,tag:LDbcQ+o2HRh6IugQuFfhWA==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:7mo=,iv:d8gal2wPVvUw8T/UYC1fyWsAoiRT/Vjc1Qpy0savn2Y=,tag:68uz0X3VTf4J1XyEF+1T2g==,type:str]
app:
    domain:
        cookie: ENC[AES256_GCM,data:SysIqZy63I1j9kjcOQXaJQ==,iv:eJBhsnoC/PedAXlm7BpoH8RQNFRIBu03Nev6meXPmhc=,tag:36nCF8ql3ifL8NY5WX+boQ==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:p3Tayu4BQ4pp7oVhQMKmqk9XKNg=,iv:0bSQ12nNcLdVby6etp8N9anQaVrUpkcdGc8giyS4qfU=,tag:xaaiwzcvv0chnmfY32sEuQ==,type:str]
        client-secret: ENC[AES256_GCM,data:ylau91XfrAH1Rg==,iv:e8FKfq3hmNt7+0/8mz6oVh+KpNWM3oHrd0NINKp4ev4=,tag:ELl86/LbtSn53/lw+uz60A==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:RyW09xb89ZI3rVIi2/iNkPwaN3RRekv2instzlTDuhgJKjurad1mrzspZzX/915o74yOEGHZxUVMcS2T1Iktb7ZRqlCM8UIO,iv:dN+ECkb/tDr/BoYWqBdq8ZjPvRCAgLmmPEOAh/lyfY0=,tag:fH3Fxn6X4buSWMChRnUE4w==,type:str]
        client-secret: ENC[AES256_GCM,data:hPsFEIx11y/SOiL7VUbr8NGrEjssFxRIeHbdg5/VxdkrH7o=,iv:Cv8k9uaXsnOL4Pt6Std9xSPB8wxQG7vPy65CNLtdeVY=,tag:XuR/OVzMm+u7U+36CC0i7A==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:fGDCgCMBixyKllPywRtzPqiXbn3xH+wBI/i1UpxfJOk=,iv:vJgomx53bLRVcpn9EvgzcpvYCkeqcAil7C1fPcKp31o=,tag:TjS9q+09xx1D6NxiukEmAg==,type:str]
        client-secret: ENC[AES256_GCM,data:XYu6RCgp+z4Qpxk0w2ZFIZNfYbXuDfdGzNZeeFSCuQA=,iv:aNP51xCe1BguN+L82pF2xglwWcQOtei08koDmZVBqS0=,tag:ptwotAl6ve5NL6vfslbDcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-21T09:18:13Z"
    mac: ENC[AES256_GCM,data:YMARfBEbBNyxg1XhYzfR6Lok2m52rBmyJuL3Ew77l1KiAM24iYrtuLWxYuL82v5N4o7zbcTgiFx6+Zk/1jy3otETSjRui4ueNCTj/VYrZ+OuqSIIVfcZM7v3Wf0IpMdLpvdbrV9xNvNLOjf7C/gLMyji4b56V/P/V8K2zioOLpo=,iv:wvSRiW/eFL/LgQBLGUDOEgF4G2fcW+tadUqd4E9Q66I=,tag:JsyFHVW4znxaDmeK86UMmw==,type:str]
    pgp:
        - created_at: "2025-04-21T09:18:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAoCXs8PBF+zAkjhpXkNEX0N4j7ArHl0niVuhkWXtvWbiE
            Bbsty9JxEqbCe/BDtnRXByuqV+6vU871/KqcLEdZE/cJnknZpyY0fff88EpO/AXh
            fLDSPiSLqPvhYwOATWC+YrCWJxMprOYKux8KxeTGS/ua3Z4iwbazEqUmpi0U0yDW
            myuKBf/KawO1jAruuwtvhbRqMHKUdM3O+rXQEnU+inqPav9PEWdd+kgQ4V0mo64h
            +uJ3wlh0c5MpY0ggm+FDVfmdkmfeQimPfHYBH5dFpUP4w/3j9gkM5CrVsE1ffen7
            mLWJwO/TyYP9Puq+hxlcf8gq0BnpBK0H/XOhx0FRQO02SQDITLyMzKh6YZYEBpzk
            TdoPIzuqMveYjBJj9skCi3WhbE3SlGPj0LZDD9n2QZj/7CmZPXkOxQxIALas55Vt
            HR1IhzYg6ZKPIh5nXuyhlOhUoEvkjoYcojoMvr4emQ4z2Us/THmLkuLJWAuWZ4J9
            c8OhyU+lNf1bf51o5G3tQhFIgi+kPeKQu8mqjJfcSUVZgruoHN491+boyjUL93HS
            aXjcVz5wfihJRemdOmv6JpOZWPokGZibQbtTXyMEX7dm5rnvV0IHWREamwC3syah
            hem14HsyxQK9HPCggr3t7/uCQEsnV1QNL0bUfpm/oxq2+RroUmqYjteji/gU0GHS
            XgFCZaOw8HYux2irIjsjrDcjKvhp/znTCLUQXQLaq/JgNJvNPVSgF1XbxFKOUQHn
            V+yIDRMtDVX3kBPlxeHAYWaG9NjyitV1VaHFtaq5BXK8mTrTr/heSKTyDXSnpCE=
            =Bt7D
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
