spring:
    profiles:
        active: local
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://mariadb.phanescloud.com:3306/replay
        username: ENC[AES256_GCM,data:LpTeeIsS,iv:V54G47NDIfqkXbO59mcmYX8xHq+QrBHWZto7d17nreQ=,tag:cpF7tQ3Pco93Ggoc2+OyzQ==,type:str]
        password: ENC[AES256_GCM,data:Wbs/IcqpjwGlLqg=,iv:AwKTJyMFKIKQ1MKxQbBa1u+w2+MZo7fvPdBuMkbwdZU=,tag:9tyPLUIxNRfDugmxUf5VzA==,type:str]
    data:
        redis:
            host: ENC[AES256_GCM,data:NSeeBkZqE5urH6WfZGZ6LyCbKDeQ,iv:qxiKZkc6z6+SFT/Vxl8IdgMBH7son20DJGaABzSYxYs=,tag:CZ6qZ1drgToudilwxFMn+g==,type:str]
            password: ENC[AES256_GCM,data:Y8dhkkvjfMkIREg=,iv:8vQrIlt5NzSN5SQV1zJQNPLj/D49eNy614tgUF/TS64=,tag:Qe4opeXm+z/kBNMFurRAYg==,type:str]
jwt:
    secret: ENC[AES256_GCM,data:Ysd2RoC2vRDSJoqH8Zutu6n+Zqof8zh4CeMHypF3dhE0JMqrzMHlYPcjWS4=,iv:cnNubviGL61IOY++6+l9VW1nx3x5o+ycWUpFxfVAP3E=,tag:ArHFqgZ6aT9ADmyRHuA8ug==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:+emV,iv:5nQnmv1GI/g1IATNytDQiI3F8DYGT5M3R6esmZAAHa8=,tag:SeJGw9Ela529eLqfoBFceQ==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:x+c=,iv:cRLWw++CXEt/hJhh9Sd53I38imWsdcBGt0ymUQMZxiE=,tag:l2Js/bdqe62q7T7ouW8N/Q==,type:str]
app:
    domain:
        cookie: ENC[AES256_GCM,data:vZP2bkFDs8KXKEpia+fb3w==,iv:syWEncOKmQy3Z2sh7DLepNz8xJ48mmZXhfK8Kt7iwJg=,tag:ErGqbzgyEW1UApEh4x0KhA==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:xFfTzvc7UUHL9FGGYJi39HnJTfY=,iv:rzv6btS5uG5TH9ZApOMk1Xg0bXK5OGd9swBKdYPV0dk=,tag:mn2bjq7Rex8dHJJpGx0wlA==,type:str]
        client-secret: ENC[AES256_GCM,data:ZCD2OycF8F/zXA==,iv:wjS2GF28K3xVJOoZo56i4J96j+SYHg5icB/Wy89lfjI=,tag:gCdMwu83JM18rFDiXAMdPw==,type:str]
        redirect-uri: ENC[AES256_GCM,data:EoaMAFE3FlfnImx46+Sx0poX5el+NVHxURbmcLnea1nMVeG217mpqRrm0Wt3s3uc5ElP3plLRAREGQ==,iv:gijpIqC2lN+D29+m5ry/Oh3SVOvFoPKCnWHgA0rLJF0=,tag:z3CzgJWCdpL03+pQxtngag==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:lqeoUTQwn3UmtegpxsaSwiOGvi/VnX31uqFGp8ZdoYk077aw9YIvcRjThMs15CnGY/0K4O/z3KD2fdPLnxJiZAwBpjgGN2nJ,iv:sk0PTljpeSMRzSiiydjOxMq2rjat04DbN35+FfDOEvo=,tag:jyKLSAKoRPQF/HKbpniYuA==,type:str]
        client-secret: ENC[AES256_GCM,data:05Im8JHZ3sj7/mW5vYMUrhwtwdLgswi9ErE5epaC8dY2HLA=,iv:9fmDfwPmomPnzFDJnRxoE0DILKncauqF4XKEUrTcwhE=,tag:Q8PEOmByif7/4RtGPBrRlg==,type:str]
        redirect-uri: ENC[AES256_GCM,data:Y/16OdvmYMy+ri6buZw2UFSNIyla0AKs3g0B555dsuJCJ6CvrAoyaVx8izfDVMfiHvrAtVq7xlKU2+4=,iv:9kHCU7FM/HGO6fttCEJCb3ub8hJI6j8EGLh8FoY6FFM=,tag:YOGZrJJvxEy83qJaTYTlzg==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:+om/wtM30GutObONkqKhjUtf7C+sS5VceZ0Ol6Xubi4=,iv:hiQHkDcIrmJON8GiQVEYFVdQBd0U3gIWI+QOr+CgW3E=,tag:NkVZ3lCMU0bOqzADUFRvRQ==,type:str]
        client-secret: ENC[AES256_GCM,data:6ThsJqtjEfYDC3Jn3uXqAjcWNo7BfdnWwof7ckWFm3I=,iv:FdYdxC4lVw0Eu1IdWQP/DhpvRyXBDRItjzfNVCVHclU=,tag:KDgmRiU50+QOa6m8m5/JWQ==,type:str]
        redirect-uri: ENC[AES256_GCM,data:AVHqVnbAlza5DJZu18MD73urjpWRialQe1wbVtXb+IHVPLIQtWHag0J+fxAE7li3JlIVbvw32pnnzg==,iv:8Ujkr/7V0N6rByo9ZYS19oCMBF+L3Q6+sOWWJSKhp3Y=,tag:qNj1EZ32emauuXC/8e1UmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-18T14:47:03Z"
    mac: ENC[AES256_GCM,data:axmLmlWt1Vhgc112xyMrCxavx5FZaagYRb3jggM0+olu9KDpUNOp2yxJtq1Ih64eQ8wXs1zYOcbK1yrCU3yLyrn7QnzMft+7QK3HNPvXelL6FkZ+NPD8YWzC1fiMHcxp/HEV9KHBiYTzP/6m43bsCCfHKgCqZQkM//fXKdsDbZM=,iv:fSR4jW/lz1sZNQiNh7uhifFMzz9aKh2qM/I50dZX+cI=,tag:zdScyRU4lxWZ1J4+6Y3l/g==,type:str]
    pgp:
        - created_at: "2025-04-18T14:47:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/9Hp7s/qVbJ3JCvCB3azQEkESBtdRYAFqfEbZ6bdtWVpfp
            nkp+7VN3PZvqkX/wr+l15fGTpM2q+oasHoLZum7y8IYUHxuw8B8MAPcTj4qordHL
            zuAGnR5kxVa0u5OQD3DnP07Bx+amZIvWhyLD1CKpFrCz+phOnt0cvyhIeRv2cnVd
            RxQE8EdADVGQFlt9je8/oaBJpeQ25yWk26QDXR50uuoECRj4jIwqniOHG83V4W4w
            X4WNPdTEQI8BX4Hn7pPfS0INTLaj/k1vQDzmRhW717E7ARvn8bd2SS8GMmu1yDgF
            kwn48FNHVMdrDyitYBWL8M3XrwbtqmGxIX0i7PzBfpJ2Ps96XJ4sG5Jp49ydrxU8
            v/OWhwaxPnD4rnf0sTpSAEFimQCZCrNZNlmediEdCfSOx//akbmcMWfl6cExNviN
            shpTN1B2xWnmav1bpTb4jgbGDXFzG6zyD0eaTfCpK+yvjxtviSNhgQLDVBhfc3hG
            A2O+pFUxlsqdy9YFyF02q+jemqDDY3SSU+bxzAqBa13rWt0O9nE2eOeCBcGf1xsN
            JFpZdw+TqO68Y/z+7HZbyhssjVzz9tXzFd/aLuzXkfWXqc5U8eOl4LLM8qpUwyak
            mepIYctUxFZm8j/n8r4VwjEVO6wlm5zLudpMikkpVGOxHXC63YpsIr1OC7Ww9V/S
            XgHiRpumjtLyAhzJXo/NieGZbapTXQnRmlGDlnB3nnA4wucbXCMX3bdBBfMtnPgS
            Z1MdGYXSIFqIqNvx0zhuBhaWY2ZFmn16l+VywZ0MiSdZi7ahh4R7ufBOm66MWAI=
            =E1FF
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|username|host|domain).*)$
    version: 3.9.3
