server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:+XQ+i3Dc4sbtF1KyNj9XgCgdjojM28Y/OGo=,iv:SA8tjpjL8yPz1P3g6XNWR4qrwIOw7xw8hQwUKLguhvU=,tag:jDt8sl05GVTO1aD9Zrc1/w==,type:str]
        key-store-password: ENC[AES256_GCM,data:lsqMQudzEVvrgd4uqxvsM3BTe7I8ph0UeA==,iv:2yrudsZn6gyE4DRPWGK7nyu053u4ttwFBEjTHYs2OnA=,tag:BbfDS67qRSDx+4eYiu3Jdg==,type:str]
        key-store-type: ENC[AES256_GCM,data:Gx/qWyRZ,iv:FM+ClgKKBH1EiMkU5cv5ucDwF/MwbbwPC7pCXKqatSU=,tag:B7nvTQsVpMyYOwqR6kjYJQ==,type:str]
        key-alias: ENC[AES256_GCM,data:nm6cJmL6QoJinA==,iv:ymMbV9y+x+5mmJ/covXSxXvYfUBG2X4OKoVFwcWvWKI=,tag:p8A7ScfO7wicjZvTNLw4Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-18T08:06:02Z"
    mac: ENC[AES256_GCM,data:UInw+Z+wdrHXaI//bUVufSTp1BdQ0x6K5PmRR4iZp805A/ZyeVExYuid5DVAgVUknVbW1iJP6HPjK/tFi9G8rJHBzZwk/MKywUMqLTJuPhMxy2AbJtc/NWQg3FrA3keJ3widm6+Uw6vgacDi0GU/eNFBb6qKob+NGYZW5wKRr4U=,iv:2vxH3SszSSoZVFTbS3LQGVRFeKlk5lf2bM7n2k9dOT4=,tag:HGAF9GhpG9O0LDQEBmk0vw==,type:str]
    pgp:
        - created_at: "2025-04-18T08:06:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA7rDKTKAOD5hz4I8Yhy9fpCqVGlu93aidFlYizN7U7whV
            3ESOFpVLh6nB8vFp4eH4K3VX+6x03/xi1fdq3rD7yxlQTnOXPMbCzqjGTzTr/+kN
            2mkohDEzN1txoRaNdaUfEGWTluzNbTTu7LR63yLcSKTbeFqOv9R1oWb2hoClMbxk
            i3ZvDyHBF7QdWMcfqv7VnwR25hzsXARVCa/cpQC2SjLS0R6IE5fLYM2IeCf7EZaw
            ysLJNlOajHPY60GNDxIeHBzoe0h9eCbFxKPYzCUUU2YDpbAiq5E5zXLH2eWNd7Ub
            kxICzgTonBADoq+8X0lcO9FLNHQOQUHjrZkqol5i1mrC68P/8SBM51b4QIoa+Jot
            cfOI2WDA4GPqw1bgbPNg+agmkXWgT3NaeO1Cy6W0iydA0FS+uwydE8CA71mqdp6L
            /r+y7wFBdbcc3YME3grKUQZ38xZ5LH0yE8vxpMY/zCx6TPb8N/pB1NhftY5vCWcP
            7hX3e7NX7AdbGPh5LztTJ0YmfPjGC26JQMxBAcA4INdSrGqV6YchoLYsxv6nznxz
            EtOkAf4AGgi8KGPwWBF98UZpIaqmb4KQFowv3jbe2wZkFAoraB2PumzkEqEVYOg1
            HqFYZ9K8tFOdeiaUqt3UimAJTWgPGJSd+5V7AHa6HqpqRhGZ1ZHEwcw/eEOdbinS
            XgGu2sEWeQqyIwkc9bAckA7QvqOZuNVB7/YYI+RNTacpIF6cnekbSpn2o9E86b/y
            JvCSPaZHZjbU4dUNHDZmcNEVUIhWh2W6EMLbYnzo98nE60foqh4t8qHy9SOeRdI=
            =2Gsp
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(url|username|password|id|secret|uri|key.+|host)$
    version: 3.9.3
