spring:
    datasource:
        driver-class-name: ENC[AES256_GCM,data:slDCagZ9et0r5PRA0Z+W+rMhBV6cNO0=,iv:7acUrVKvGqVXfggZIsdvnZfXUn0kRL4mbednD/IzXII=,tag:WhenUJHOzk75ckB3zYEOmQ==,type:str]
        url: ENC[AES256_GCM,data:wcWSt7VY8CEZAHsP4pFdxPV6gKglvMjS8mI+5DehccBl4+waeTJ+ryv4arfkJlVXkxA=,iv:YbAfB/Ye5tY89bLZ5V7wk1mUH9zs158VJXBKz5wTOuk=,tag:iwcsrxabPZb6vvB96N2Tzg==,type:str]
        username: ENC[AES256_GCM,data:IJJwqPWs,iv:T+MPJTdA9WnnmjRALHVESWRsMVvbkKBfMwDtvXzCdBU=,tag:8KkL5TDGzSeZhpYnNBWpkg==,type:str]
        password: ENC[AES256_GCM,data:iSQHmYnMnu23uv0=,iv:U8eby/3Ayh5iY0wAKotA5+EFjc+C0RZ6rf6p98DYzv0=,tag:2Tx5ALC6aWyqlKR7sIWSSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-13T08:30:00Z"
    mac: ENC[AES256_GCM,data:IaFqNmGNusxvoU6YSI+T1EQZSffK1VhGHdY0AxcRV/j2+B6JeBKYN0dIOEsvNoMnuZ4TuOMxdYpziJ6nJUqPIdya4r8nO+TnI3ukaLpXjmy2yb6uONew5m92hbTK1TK+4FimM1YY5UjrpGyVH2Qcl0BFoqDMsg3o/zNrAhE9Rh0=,iv:rqvU7+We8tKohTY3B3zxKr4f+AoOLZH9Le5VEY173Gc=,tag:ob365xF0yxNG6f678JSXoQ==,type:str]
    pgp:
        - created_at: "2025-02-13T08:30:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAjHTRY/0KBsqrh/hXKf5bLQz6zNHsW9GVMksJ7fpJJdxm
            KltPPQftvsIMeiHcyf+bolrGaOo1pMO31ai2iaMfi/4G1/u5prCh3nb+5bWPapmo
            biVU4FbeTrw4iYy63Rbe/9AuQooMt5dWy47RB7InbNiC/hPN7MyKwji47dM2Q7UP
            +TvPamwiucbF+W1i5+k9CU2k2i/0WRt8UbcA5J8KhXB+xHPlachHrdNh4+2qfP4S
            Dy3o749PnYgwFYLm6PEzFeT+zLUyeqYje2RKcD6xZH595qQHnCmHlrAcS1bZyxRf
            8yoSCS1xZOkhD4fe6e9orqlOs7Ez0C6hwMFoejTXUwUfZwPFuaCkzgYRhRbnkmNF
            2W3zS1OS0eVEDwpGj9v/18q9NU3a/P+VGRjoVqyzMBYvCLjCthWTgFG5rmvTP1Cz
            7nEyZQTxJnbh69PyauuZsDp8QxTKDFP3SX2dijpvxPvog8GcOildDKEFWbhHagcw
            gN2gEvRrTwnqDR/DwJVu8E/j8G6gpZp/8BXxLIxcTu+DbVR7EBT6jYDIexH1q1dL
            HueEyGZNAwagsmjxhmeaAtYExO2aXmBB8at54wcx1Af087Nt0JIhpyqNbRkHss3a
            a9WgDfGwvKu5lVoPsc3WBicH/SW/EDn6IK+LCK6w/vBXoFWQchESN9dFAve46KLU
            aAEJAhDBD6Nf2F+eyoigqSuB0pz1imw3QB30ZnZQ2cbsxyEjgEp/5XKEcTVcKCMn
            ZD/KUWpyrQcD927DOhazOS/jQ1cDTjEOFlXYP8m8TLoRrsPw7auRw/kMdcr1hnUT
            R+DeRmFeoZ//
            =6jLO
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(.+)$
    version: 3.9.3
