server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:OUYzEdqzSVqmBNynkz3bmffussIABUpH3gk=,iv:bk7MDaYplZdHrBFQ9aBw7LbjQE4Rw7QnaBQLZfhpMOw=,tag:N8LoNo9mX3UV+kWvBqGP8Q==,type:str]
        key-store-password: ENC[AES256_GCM,data:Db3inttKadGckdrwI1odOFtJ4/mWo923DQ==,iv:GR+b1yEuZVuL3YK/rhudFb4HKszzUrFBOhropEupNuw=,tag:Zl5oS01XqGFJ+KnOEbVrxg==,type:str]
        key-store-type: ENC[AES256_GCM,data:XBGLa96j,iv:n7DQHf5A+0/RydwZ8IZmE4dSGfkY5fwFHVKsgkOoS8s=,tag:V61aPkJujMkGexQukXmALg==,type:str]
        key-alias: ENC[AES256_GCM,data:zsJH8lGLXUholw==,iv:f0bHCnyrhwVI/pj6SmEYu2VUtkUlYDo/V7isSHjoaIc=,tag:AhU3vMUfGgPfbLkGoYnM4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-18T05:33:31Z"
    mac: ENC[AES256_GCM,data:hMeIB5SaU6f/VgrvdK/mjFe3Y/3Iz/iZRR7YZrInAeg/Ruvl5knq6pEtFXhZpibeob0qUIohNtBATKtFCuGimoiFTjTZzlWFt1Sw0Dxs+JsIC56fNdPUzTg81Ckp0WfX81VrZUXiZOf9+9Z7QmAZElvbLj7fX7IWnvIHvxAYcMI=,iv:zhVGSnndZPEdiHPuBL4TrEH75nDVA4GdsXow9ung/Xw=,tag:Ajv/zA2Un2zzzl8uLHhK8g==,type:str]
    pgp:
        - created_at: "2025-04-18T05:33:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//eoMQ3l/9qNSfTNSIYqpMKGfIWZFVveSLbFd46CyML3Ih
            aQ4aT1D0R3OzUt+5mMfFKxouueJHZ9y70rlKI7O91DE35G3P8fZAm0jFF4o62YRj
            NB90VotcSazq41L8qFPqOBjchL+uuvE6LdqgGhOkygtzT7+vTu8B2Ww7CgDJVh1R
            DfvNHvxqONgNIZkHgWMbVgcu96XPijfrnCgWorwscQPqTj2IlKwTuIRCqPb1OX4S
            F8A33RjhLA/KMEd/q9dvYDER5WVyoqciiKEPwpinR9oJdwoErRGIGR64VtWceQPr
            Pa2xm0PsT7HigwkenfHGCjdLlC0lo3zS8azfSn1tVL0MZaMNouvNnIlrqjv/ruac
            TBgMrRzcov3zlZ3vI7Nmo02vyhiOO4yto2fy9qQtVBPEse/jROfpZuvmAbUeATcJ
            0Ago81EwHiq4EmzO3zKTSQ9UjQwenS1dDDzV8xrGNnsvCr56lCE2lYwcVlpBt8dS
            Qcn6aaG1koC3XTK5gTg1/s6MUHksysOcmjttZ6Uop7+22grnp9jQ16+iYEZp+UtZ
            wKHXRoquHj2Owh30/p5Io/4RwJxsNsBVUNEOSjx3rZ6dQY4f7QrwIj9ApfLMgbv5
            CGEJAdwOdOdzFMJpEWGE78rClNueG/disncKDZBDeHbxhO0LkmG5IpDO5Htd1EjS
            XAF6PpPL320ubGWwkjomCrGAstPDjuZre6LBuFe/wsXGC9Pm+mmS0t4Qf/YB4XqM
            sdWjYqIgRhb6qZDSzKSBAkEpyct/gnFPD3m6NsHwZtm6fMLiXmFHk6krIpuN
            =8W37
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(url|username|password|id|secret|uri|key.+|host)$
    version: 3.9.3
