server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:Gn6FPi0RogV1qilWbvuK5roIyA==,iv:c5r7RYEznSfviGHdY7Lcl4IDdPIi9deQuKgY5Ua61Jg=,tag:tHKXAZtgbGcXEk5OEEeTZw==,type:str]
        key-store-password: ENC[AES256_GCM,data:UEd3oAN1cIuy5vk=,iv:AQCHv8TYEpBmWVp/rKGaRPU0hWYPdARcMfUyDnHaesM=,tag:9g9hfrOZwQD0dak6NIPg/w==,type:str]
        key-store-type: ENC[AES256_GCM,data:X5uKmwmE,iv:a9qXkefNGnAN1zEQ8aTkN20rrUEFFoTopF4Fdw28D/c=,tag:0ZyxqruQ4IKfOp6wjDeAzw==,type:str]
        key-alias: ENC[AES256_GCM,data:T9Nj5QHq0e/uPw==,iv:5GtiOBSJrB7SaceNyb9dpxTEbVfRuxPoyIsXwuU6+mw=,tag:64Of6NALYGOYAsvM8WOeeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-18T05:33:31Z"
    mac: ENC[AES256_GCM,data:1BYCatYRMM5J8qRnUQMZKLFX2mCoLlpigNVD+eTkaWXmQ1oTt2WHVJUA/keT6mW+VxussULNX0mPXK+bhaxSET+if3/DD3c/ii9mkrqFskSVeXGKOjbFmdoWnFRJC+R2VVMRvVbXmJQBzEjUqOepbF5Od8MmMmozpNQ7CkG9bG0=,iv:9EMFtFICZ0yBx9/EWN6JQXY/OOaWtBGh/0VgFgVhOnM=,tag:k7FMJRhqm413WLvS7jOdbA==,type:str]
    pgp:
        - created_at: "2025-04-18T05:33:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/8D71mITf1puYLlZr68Hqg/9hNKXkGY0X0RNjJeG0goPCb
            IDvpTWknnnn/eaJ9t6fKfKJe+iHkjCjMA1Ha229Ill57s9tYL6vdfvmc2AEewXlW
            vsF0gXUb7AbU94tzPC9hEWKv2Asgpv52VT7OsZaqNYGaW05scwSb7RDUjE61pDPT
            wEt8eSAIT/DzNpl7MdV5yIBl4U/we+yjnRXVlV4e+QzMfmxaoNOtQgj06O6AjnXP
            xzn0Z0x3Bhd9jllQzvQQWnMMc/qV07C0Oo0KylLRflnt5/abYD5oEhnKI1JjuezJ
            bqkqWEIV7sK9ptDG2lr/hH0UrYc1TG3gZ8WbEc2R71y6floDCZuI5EQeCFlfXjAj
            JDKEqK95qO8xneLEk0BGUWfBBPnHRd1Hy6K2vQiDV2OpJDek8u1QgWSIlvIlpLP7
            ZwzTolt41uQoGTAfi+fltXcuJLsLb209+wLooF4Lcj6eO59Zs1EFucNwmX5y0KvO
            VzZB9CZvsiAvpYarDDUKMi/VQk3rT3CBVWieMcK6tT15QwGWwNLUEmSbCtyl6GdO
            ejQEHoAEqjL8zTVbBr4JqiPPVg1rhk3YhJZYdjXPOT/EDhNfrkc7Facb5e/hDA3u
            XoQamGyCYvuxFpUd5knyjHp7IHRNlETkUx6EPE2Lm1XFijY4FJ6QsH56Jg6dw0TS
            XAE/efXmaN5sqM/M25AkKmSRlUah4CZApos6IUg3Wx+a92GqakqgBDbYKqIZRXU/
            XMYWwe6kp58kLMzUe911p2EgLxkTBhJQDLRMSzJNFpfv9eYxT+86Ki05n0Iq
            =MUOw
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(url|username|password|id|secret|uri|key.+|host)$
    version: 3.9.3
