server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:QJPNzXeC0fFQses3ffKyyMirAg==,iv:WJWxeSR4U3ajMvW9WwK4FvabigT/JhOqKrL1xbTu3j8=,tag:kXJh9qjhKuIaGLdGQfwMPA==,type:str]
        key-store-password: ENC[AES256_GCM,data:qSBYVtYylJgyEYs=,iv:Z+InNog3Gq5G+U6Ef0i4MZRPbDWA+MtAWbUH9RSJvHs=,tag:MNQ9Red+FSG9EUp4cLjU2A==,type:str]
        key-store-type: ENC[AES256_GCM,data:6r+PRJu0,iv:JsGvruIRnEMtM+y1LmHf29ClX9r9ZA+v3ixWjteOUDk=,tag:9zI8WlXgO6rrXgUchSW7rA==,type:str]
        key-alias: ENC[AES256_GCM,data:w3Wem3IEz1T5IQ==,iv:d//LMLYPuxMfd4z05ydNVpPwQyTp8FQN6CjSWH7/hZw=,tag:9WQCE/Bw7Gfr4ZM2O6a8/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-18T08:06:01Z"
    mac: ENC[AES256_GCM,data:m/X78sJhtKYeHojpb1XftwpL95bpdVr7Yy5ERE1a6Ibk26midxmtJLS6wym4q2rsZ74ThBzqa6dTdhtCLXQQnACpgWWRYNvcBrsjG4p2IRIB9YYZ/8Z0WHXp7fWtrpvaUScoRD3zuI5ftcojZGBhAsCUEwYhswpzCS5xNPvpc3g=,iv:KomNR8KVEx0re36OwUQG47tmT3oPiCqCpAOyrZnEofw=,tag:Bq0krCMCB497YM88qgaM2w==,type:str]
    pgp:
        - created_at: "2025-04-18T08:06:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//RwjqmA9JkfQsrFWjXgR8aA/uAqiF04N0q/91K/F3R0XK
            MtZig87xrvo3RyZh3j7m6I3JkNNDrO+iysmN91xDOmhDG5uyI58HAVLSysCM+FxN
            H999uBajuaJoBQmFqvwPNX0ujLu34ql89x606yZ+qyM/9V3Z3oK81N8kuPm5PwR8
            ktNhRb22A1ZO9VZ44yaTk9I+usxwr5XFJsFxWkfBvibJ6hdym1Sn+VEOGLkOKPE8
            qhsFOT6FIvrGwh7wFyeS8TM+/2FFU9S33FhS41oi4hSD4yttj4NVHGNNLup7+fd6
            TX0cYxgxhqLDFo+qAWtkHgtwQelbU66OLPg9sWdbnANWMtNCPvFhwrhNHTz/xLsP
            ooQRVmz4HiIJdLEVB1mKmXtiqCkb9H23rTwMwY/+mdhU/2NaUhHZ6XgmYVojyJ2l
            +ybL0w/FxIMKxnOGgS4q94kCrSiYYT2OlP7Zo1SognL/v9GBUTQTGxD/WsMtaSpn
            k7YC55MMhFqNNjugZvH0x0ZFD85WKVLikFAdYPkG/AETfGGZoeFtMQnH5XoJ+E2X
            btFLItX+Jhp0emlji+fospV4OzDGrY34hHAUBoTEfJ2l2aS383VF87XPnANN+pGw
            ZqqgPpqKT3tBJsoIaBnZWvs+5o98Z4ve2LPIXjCWAPaJ83mQd6NWWXFW8+SkhJXS
            XgFZ3KQdTg0LzUj2y0fW+2R29klNj61gKP8i4b5qE8x1U3673waz2xkTn2Js/IVs
            sw4WZX1mZ8WZJoKYulfgpSfrQjHT0rOSapdhitmboh8/q/ae0s9DdNXDj1nnExg=
            =/qvd
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(url|username|password|id|secret|uri|key.+|host)$
    version: 3.9.3
