spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:DVy4xUEgcxthUQ79xzjUq5yHosICG9A0OyS9Qqj5pt87QsDQxezslXM=,iv:8v3pmXoeFDVW99q0f9Z/5SZUm3l8KkQD+CIPCOlpbxg=,tag:ePUGk0kbie9ICEcN0l7g1g==,type:str]
        username: ENC[AES256_GCM,data:Gb+Se712,iv:cGjbHAj52X/J4NiMU6ZO1kZqveQQPODWtlq4vTxAIA0=,tag:AIYB9jkekXYeAB9t9zJ+8A==,type:str]
        password: ENC[AES256_GCM,data:E/tDEjgEw5tNAes=,iv:R7+DN8wL473T8CSomLthFzM5m8vWIgEI4kPOSYIwoUo=,tag:61K6RNorFF+HuRgVe5GihQ==,type:str]
    data:
        redis:
            host: ENC[AES256_GCM,data:R62aDVUQbMRf6OSN2qm7Tl4ulhw=,iv:AV0zK3vNkzW7XqMgOiaUw2gDjbJpC3Gv2WcR3ty1SV8=,tag:zG0RyrI2gC7d3iUy/unBzg==,type:str]
            password: ENC[AES256_GCM,data:09g/4187m1fMDWI=,iv:b5WErJ+wgsbSTynQrJUc1g62uCGepeK8jtq5FTuDMRI=,tag:u6Y9QENjSgJUeqJ13/ZAHA==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
app:
    domain:
        frontend: ENC[AES256_GCM,data:cU8ozy2/FWac+DENLkgTsQU5r5ucV3fzTHhfHnaY+e8McSQE,iv:5cc9wBj66AK6oFmYmmVm37w+LiOn+ReJgML2l8gxypw=,tag:noKzOaeACTaqoKFxNeeW0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-19T16:28:31Z"
    mac: ENC[AES256_GCM,data:l719IQBr+h0mZexUCcLkpEbUmp3BfFDP/PfErEIwC+a6ccpUV9LY4xk9JE3vXOioKpIpkU4cWUevLJUoHlSlsKQiMdeONm8MLl7cOJb+XdAfpp8x6zlUABtxVlMagj82E/ZOo4Kw8q4NE4X9z2nPvV5t6A8GUOQPi65ISTiRdZY=,iv:IF+QVpQIhjF3WWertiGtwqFmBs8T5PdkGuOZt3nnLAk=,tag:K77xNLIZOwgvvLmxp9OHSw==,type:str]
    pgp:
        - created_at: "2025-04-19T16:28:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//VJgZgpDB9UmyAJlRULZHdtcO1hzKy2xDAn1w32XZddnc
            rF9gN7embuieJk7hUUKB2wLAXl8H/Zi0BSAKSaeW44yj/akjkWMO3DcG8mnl3RUi
            Gu//Vc/plRE9ml69eP3wuXbaeO/gxyn+xFzdXXriKXlnaTvMPfan1uq0BTqNXCbK
            FCOpha4N+7hBrp9Jyu2ca3wCH1vVv1E7BvN/Ln1h3lzBQ1q2kZWwKv40cU88pW6I
            oKDOKBNbg7qTlU6Nqu/7AAldzlTJeMvlawlyq47U1fCDVE5sNOM7I9Tw9XAiffT5
            YSnf2lPWWrPg/LwnYGlgzBjdikRsvwoodtZulLyUaYI+BqFx8G9CpSS9HAzvD9cM
            9vk1wBKP1ycgu2oU54xCul/PNalCr/nOXzTlrsfW5kOt1ePenypwkP19UrBfcviS
            Ls7xmE3CssTa2SmSUol2tUOtYu3BPpX0Nw1FFvCBYdj8ETs63gITvGVD4tRH8UJr
            CAGVqe2ORJUzoNNPicNg1ihdreDMFloavXp2ZYVkIq5Vtr3dtH+EBq5CMrszjgcS
            Zht6Y117i+2xC6Dn0CK0P6BPqYqbozyI6Vao1nE7LDjQsN8RwutXljMvRguF4nJI
            oBfpETdSYoNslTt1SzOhKvX1Ug/+lGRErN1/H9fpeMEKxOLwUCB5Kqs7QmSZXqvS
            XgFLwLv8kJFH5VxP827tGofTo6EoBzs9Fw1S95+guRgWNVQKQbeS4zhMO5QlGTil
            B2R97XIbZ7FC/ualn/68ZSEHlyxXXIc/cLYPD/PNIhLulynLLwtemodriOEwyD0=
            =XotJ
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
