server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:sOmAIKsGM8QGUOWoRjLNylIrn1winr2df+Y=,iv:p6FstcOsjiIDsS6KkSCAPzJCmlBEIvJS50rE/tyOMOc=,tag:A/5VV5puU5IN0XFfpgBTlQ==,type:str]
        key-store-password: ENC[AES256_GCM,data:cbbfQ1TOd3XJi/yIqc0ENzs9oI2c10oxug==,iv:e3L/oHTn6RH0JnafPJpc9NCMQTozeoaxi7JIuQUgJrU=,tag:rrx5Qtzz5bvDXA7Prt3MFA==,type:str]
        key-store-type: ENC[AES256_GCM,data:XaiDpV8Y,iv:IWiUg2WgkUfwxm8MKbXXUZFnb2z2jdY06irRmMpAo2w=,tag:gpT7AosvaZ9fTeOXdGbnjA==,type:str]
        key-alias: ENC[AES256_GCM,data:cmxEzm72w85V0w==,iv:1TGcG3l3DEvk3jLR7ZQv18ubLwVUhVWRqdVK7aY8uCI=,tag:Va56cVhtx80Mfx3Jz7GqAg==,type:str]
spring:
    jpa:
        hibernate:
            ddl-auto: validate
app:
    domain:
        frontend: ENC[AES256_GCM,data:6JjyiqHdvVnAnakrSH5/mP5rC4QUCN37+7UJDlGkCOGDngFC,iv:6clpJvG9AXD78NvyWQG6AxlBfpb4x6Gxjm2YJ/KJ87w=,tag:5mAnTPFBlDmHB53r1COE6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-19T15:27:30Z"
    mac: ENC[AES256_GCM,data:Cb17n8DqPhbpHv3XGpYEMKm6cPVw+t4VRJ8jHxJTdziTNCum6ZIr10BoFL2sgQOHfBzVgwi//at8T9vWOLPxQCkGaacl6RSohYOU/3pY037NFlDcJ6OAROAyx7LK70rTV/FFf8U9uj8G7Sv9KYx4RJS4B2pH0yZl9huo7ZsIgag=,iv:vPOi+XhVEQG7K7eGMVpHBLbErR/+r8OJqXGvJES0rSQ=,tag:E7tyj021Z+JRLBxvFfpa9A==,type:str]
    pgp:
        - created_at: "2025-04-19T15:27:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//Y9R9s84/MbCxRFyL4jdPa8Ig4BiAbqY1zsE/lIeUpBOq
            d32H+n2MC7Rsedb6KcSS6EzKjZtahmyKNOroP+7TXRcLIKOIRg86EhGKon8TnE6W
            DpGL11FCIoZnAoOYuC3v76cIn22SUa0ZLaN6EJU/4eYNDNgUNKfCtUNreUiGfqza
            Zk4oREwlrz2tyOkXu50ljjtq62+49s0kCjznav8PTVkJ8g5aBAnD25nFEgTMxBHt
            v5Fpx4LvS/bDCcCf4J8k+L2XaUY3+/mfPQ44qnSiPt8EA2+3YAyy3140r3TaaBKL
            zm3VrgVP9tJQiZrH3de9y0Z+KJpOe8gIox2Drv9Mshczyk1XeIPAFBWQwftUmjhC
            MJ9R6TciFVLaj8jZ1ocKdYniDdsjKMysamYxWrxYoJ1L7efZO8/4BnkgIcjke0Ai
            sDQf7MV5eOPkwS5XnRLzMpbTK+16TSn/rvOIZnX3C1mw+LN9a2cTvQor2Z630bs1
            r4yRHEaPRSPKkwmPcoAV9YAYpGtGjubUnqrkJsKHmxSdcamVyX+d2BhmtZ9SUAw/
            gId8fXBTWF1r9fgMrNMZo9SlxWa9Vh/toqMJ+HOESfYLaa31FvUD2zmLpLGsQCPC
            UWQxkfkQKWz3ewQiCNsE2v0KFpoF3nSK7dOAx2brjDVISlcEP18AK09ygnIwB0vS
            XgFFkyOc4nJcQNI9U4Eu7cWgGExrlgqmYjYzBT2JiRbL/IGzpkZiipfv8py8FkXk
            BmdItYUMlSQcXVgrTLjwM2eb/GhJfi4ZPDGlvgx0dp9LPBKqylNQWw2l5f3zBmY=
            =u6GN
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
