server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:x3CwwOY53i7Ie9JLfiSu3sh25A==,iv:BHZt6+ZuEZMqo+GFAfDJbIhrz1+PyFeHKlUir5m2DUM=,tag:fwx3lD+nQToVp5cZ78wThg==,type:str]
        key-store-password: ENC[AES256_GCM,data:4fQs9fAvzYBqHxg=,iv:2GUopeMIzdas1bahh2wsc5AFgx2irGOr0eQCl77SInY=,tag:uEW+JkREellLq6DIh+PKkg==,type:str]
        key-store-type: ENC[AES256_GCM,data:qX2gCsyn,iv:24DPSCRoWxM7TTw0L9oBNwg5EadKtWN+o2Ftz/QQeNc=,tag:VnJJmEdErHdOrL5IfQgwUQ==,type:str]
        key-alias: ENC[AES256_GCM,data:69p0MQqMrj1sWA==,iv:/nWbx6iZZAWYPl/51lpezKV6BrW1j6EC3xW7PvgzcSY=,tag:d5VNSjrLvg9GgV/eUIlkXQ==,type:str]
app:
    domain:
        frontend: ENC[AES256_GCM,data:h2VAhquowUxUj3GSPSqcBMs5a3bz,iv:q6W+pJIlk6kVoPp7pD2e0KG0mpK/paBT53wCbcJ/l7Y=,tag:YrWNdlySSMJVG9o57HcCMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-18T11:30:00Z"
    mac: ENC[AES256_GCM,data:51t3tyeUUq44JDRlbHzOWZlu2HCWO6Rx8SgLlkMbMcqxbCr/kyFnVnNx7mlpg0mW8oa6/71Dqed8UZWoUTgUgbQwwUSMVWNLFifcdbPK2uAas0sv8BXIKMqnbClfu8mIb2QlBa5T6vKLCjXEa8w/+gNZBPQjVViPh7LBvRgUmVU=,iv:yi04xsGHoLl2XdSoEwmj6PSDAtc2zxfBN96Lu7jVU50=,tag:gn7v8I5UwXRoPL50/7czSA==,type:str]
    pgp:
        - created_at: "2025-04-18T11:30:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAhRPavY2Cv/ZByc6rNypJjzUX+Vt6mVQ/3nPSxcqiOtX5
            HyVEA/pwmf8tzBWC2tbN1X9FvyvrMmnSH6HaGsIkt1jagFk0xpaafdOy2YrraKAa
            yzbn7ycCmXM1DdQ7VhYQO2lWeIZHy3TSDOTfbNZr4g7HAnyAEDcEP9XEEaTtUeOE
            CI56YDI0E+1DZC4+rt2kHpDzPZoOGxoicMl1G4d7UDN5H/98MpQj3MTGqGtTsBfY
            2C5ddj4vpA/vWSQuom3zFsHoRC0iZBInzO96l7tf57zS72WoQD/hDsl7GVjFy87J
            r/HUzWJGmN8D++DqGBGi0vlDAQS7pLzgY/PVSXAJGfr8IsyPysMqoEQUaemWOVXi
            ZNudY4x7IDCe6K7eB07md6thq4Ss3w5/nnWGcixjAReB0l/Cueh7WPwvWPQx2Gjn
            X+/kTGm3xZNgxzIT18FkxBVAMRXxEcyVC+NcFHD5ZLTiYUqEPWftWjoblVdio+2L
            VzhKKTTosZvjeZM9fTVqIiOCDx+rGnaETeFmxVuHQsyuMzN2uMjdoHIj2TCwFK4H
            Ct3bOAcBv3IBiC/weIplklaQBRSpwoFrMsX4LdnIRCv6mBbas9JspBa9gAcWjK3U
            IcST+hXhEHqMNW5uf9WMbcM8j2PO5rORBZ1QmNV7K/RziVtEUJSdGn0/IjY4K1HS
            XAHsG7AYVpLgnx4/e9HvB8lxiLswxvDGymzkbfnzMqe5k9JxOANrmlhUxdDVYJlv
            91o4qvx7Bq4Vhex3n134el+ewLbed1iDI1f/FvCHQ6uSd9vOICdFVMag2kkB
            =btbU
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|username|host|domain).*)$
    version: 3.9.3
