server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:H4/e15b7b6IHvh4p5KaFZ/DByg==,iv:StKGwAN1+SB6V9JmtD+w/qUQ0HdLKe9eG6QycyjJX1U=,tag:g5CBsbGpOMA6+ZpmQHkjEA==,type:str]
        key-store-password: ENC[AES256_GCM,data:9g+CcSrG3Zq7bpM=,iv:7yEeFTZpUvSdwfEsgr4Kyiry6YNH/wPq+37wKim2/kA=,tag:0icJ6Lf7kzgJzrbOQkg4eg==,type:str]
        key-store-type: ENC[AES256_GCM,data:Jr1LQ4Z4,iv:8k/7kbZkIcMYS+CsAO8TezEDRcr+w8um8G6rfeEc70A=,tag:UW/04GNga5/Cok7ZQAEevw==,type:str]
        key-alias: ENC[AES256_GCM,data:zzaVqEAQ0wAxLQ==,iv:kUQKiZtWYbKy9ejg9VuS+AWUI3Fh9ashThQ1Su5jWbE=,tag:R1RLTPZtJNq8ey/ZVOCRfQ==,type:str]
spring:
    jpa:
        hibernate:
            ddl-auto: create
app:
    domain:
        frontend: ENC[AES256_GCM,data:svfIFuBqRxS5x/kZ9EnDwQe6/36fYozkcGuY,iv:qAMeaBK8G4QoNMdQPWkHuLeUQJYoDLUkRSQF8uDIAcM=,tag:uLNARwezbT9d8VUwIP5ovg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-19T15:27:30Z"
    mac: ENC[AES256_GCM,data:Osfv/1yDl4r/GFqutfp4cnVstFy8kiUOpNSLOsb0J58NghiE1AaB94Mukseu2y0mpRr6/SxMh4v0RWU/+wvXHDArHI07G5LLgyKa/33EfWB40kiuccawjEtFu98G7ABRQwG+YAnQv40V4/Xs3ek6Y3q5zp01fo/YEx204OcBVyQ=,iv:OeI3pjxxWfsEQqDGgJWJis5Ivc577OQFzQSo7uSvfyA=,tag:1sZLka/hWdBRvoGPdimv3A==,type:str]
    pgp:
        - created_at: "2025-04-19T15:27:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//YX9KkKyZNUdvSABMW8Aqbrbv+DsMinx4yc7VSA+7tKdq
            CND8ENlWRxCzL3sKlf6qfmStWSd44BoYTBqYTkud1S8cPl/xQKOz6EPh01l+iIWF
            s/OLqfQs4pULG5u5t4cKeirXp6LL0CZHMgOe5sIY5epoC0KES+a/heVUeqN8dSte
            LrJzinMbOznnLgYOZn7lduao0GTkJzRfQoq9+Bcp2d21fbk35Q8K76/F0PspysYs
            gAJtHw9L4BrbcT0W3ymIfEyjvP89RahIyGtqZm4r03AMNov3D8EnfzaEcuIXMKfw
            aUtrWC4eA5UM+/ebRTZNRy0i8yKm1J8MjDe4EZwtVGqlVBqhKvYUxhpvvnFjSXWR
            FHFams7K8L4vqkWKfCs/fZqoDWhr0i5PTB22dJr9bDrqyzoM70KAFfzTgHGiJXe+
            pZDjjacHPwwzuOzYnPJB/AlC7/zgKnl4NNCN3d2gb+0ueCiCBPth66cUK4m6AiSf
            rtnKclii8Gp3KZ4fGGnhWqSz+NxwySPO03n5m6UMM9wGIZOCa/920MwJzk/vqQgy
            p27RE5yNevvcWy4DG5Dv52YytnBjwh1inAbkBcLitxt8A3r6yOgxjCSXEOfSiyx4
            xdiGJGBFptjOuRN8VrhLOMniaG+tWJcnJYWJarILGkWqcEewXKqcLh5FdZ0RRybS
            XgHLoF5j8SxsBU/CTg6sxkJWVqmhXy5vJCO1DgUllaijt6PDnhmUw8wLP5mIqTEz
            cs1SK4lWc50OaPUTnVvjdy46iXFgSY944cFiaJYF8YVV3nQsX4sLuNVzbTsdkKk=
            =puZ0
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
