spring:
    profiles:
        active: local
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:4ltF0mUMttfMWwYzyAMQ4JBV30kyApFcWpHKtA8MSJYitHOAlgkB4FBmqU42/aMVi00=,iv:M568rDkRxYML75o5D5VUgcxcR2dzFd0Bh+L550bBRmE=,tag:jylo4uahIQgYp57oh7R+hQ==,type:str]
        username: ENC[AES256_GCM,data:6cDi2znq,iv:5p8ukYoksfFygJUJ4jjEHy+IRDHQj35j5ZWR+nKH8GA=,tag:sQr3qM7Xp4gjSJtyjIsqSA==,type:str]
        password: ENC[AES256_GCM,data:uTb0p/siBt3gEuk=,iv:Sch6zQajxVWNeqKkFmaLegD81tmsJX82f7PQcSQ1MRo=,tag:x9TcK/pcDPltCQ1nkXMHIA==,type:str]
    jpa:
        hibernate:
            ddl-auto: create
    data:
        redis:
            host: ENC[AES256_GCM,data:24yApKIKvRa64wIuHRI5EtxXKeWO,iv:olF5XPXkp93NEV0rClu+VutjQTCMspCOq+VtPFyPnk8=,tag:Vvb/5uvUTgEX//CXpGnbXw==,type:str]
            password: ENC[AES256_GCM,data:w/a2X/hY8OuSNos=,iv:0/fxmvaPnC/yI12z6SLGD2ib9BVFl4vOTFCcPVOJzY0=,tag:vWt9U86xi9aMzHhtJq7fDQ==,type:str]
jwt:
    secret: ENC[AES256_GCM,data:6q+YyKjXp2WTwS1KDNKR9XXYxSb5zAMI9t2nDrcw3L9Q9XK6UiYgH1OVPRk=,iv:yiVsoVtWYGsxa///Kpf+YVY6J+WlQMiaes90DBNovIU=,tag:XGo416usPQIzVs9r9tiI+Q==,type:str]
    access-token:
        expire_time: 1800000
    refresh-token:
        expire_time: 2592000000
frontend:
    url: ENC[AES256_GCM,data:h2Np3Qz62sVFlgHo/x3mgv4w31Wn,iv:Nsml3MZIWhWZQ42Ec1T2EZ+Oj2wVIbD/kl6jEqPq9TU=,tag:oi6Nko9jGFlbzrPgh7oxiw==,type:str]
naver:
    client:
        id: ENC[AES256_GCM,data:G9WCjPW09bMYFf6Jb3onM50YWAc=,iv:Zj9I6A3TsdASjK26LcL7bShO4y9v/mfA5oXWYEUdabE=,tag:5ToQ8oGxsmdKVMsEC0htBA==,type:str]
        secret: ENC[AES256_GCM,data:IEQg+H9FCq9y1Q==,iv:6I+R2FS+n+d1EjTMhU944HeBenP5k1EwbiN8y/NcicM=,tag:4v7qDpYR6/2bqD8TG3kokw==,type:str]
    redirect:
        uri: ENC[AES256_GCM,data:3nionYIOj+6epJiTX3Vx/R2DBHCSKGlIXBJovsCND7TkqbybzpvAJkaDrhaYtiDFUMl/JRyemswc,iv:ytOSKCGffAeWCxvfX6xmuOO5oQdWkyeGbJjb1/5BGb8=,tag:f0gofvLLZIyzTrqM/vEGzg==,type:str]
google:
    client:
        id: ENC[AES256_GCM,data:o6/SI3ZMrY7VUJhkmn1if4Bj44FRSD3CwMQAF3pm2XPYGRYibUIom3ndYYZXTO/bPL2LD50yy/Z3HhnBkb6/YsK7D5piCJND,iv:ZKFiO6iVjsgqaUTHHMBe99y8HWGSwDEvp138bfX8KKY=,tag:K4ewI2IPiC+GzgLb746Aaw==,type:str]
        secret: ENC[AES256_GCM,data:WG2eOZrwUBIo2cvZnZGgJl/gGStjpJMqVRouaB+MBk1jsF0=,iv:mTfUzzr4n7BoN5AhV8LYC6yP1Kns7cZ+8UZhd5UKyHs=,tag:veubxZoe/aN6BOpeQtT7ow==,type:str]
    redirect:
        uri: ENC[AES256_GCM,data:Yp1fC5IN+JWKUU7Vry4gmPfnnzi4ef0nEK7/QXsk7fpy1EvokpFOW0xfmTP6yFwa4b8J0yJG/xItEA==,iv:bTTZ7XdvwD81+FAnsN7wcXpFdsgQ4c6UpkOtzWsLGbg=,tag:INv5ZkN1Y5GqxBcwosV9Nw==,type:str]
kakao:
    client:
        id: ENC[AES256_GCM,data:0c6uG/QP957KeB7LOCnLfaeJlZN86oklATsoi2hosXI=,iv:TiHAjTatxwI8hGTiC6iT9whLDm2TXf+NEfbxKF5VvgI=,tag:zwfR8/hSPQdD8gZf5/tF2w==,type:str]
        secret: ENC[AES256_GCM,data:YYY+gDBby60R8oCU2wDRkPaQWdJBGqw21Ug7QhJKCP0=,iv:FzFjf8y+b2ai7dNI8SxbuRh0yPDRGrI4F0KWcnLPCXw=,tag:zbsrre/14zMfGsSc4tlZTQ==,type:str]
    redirect:
        uri: ENC[AES256_GCM,data:7Kh+QPB5efz3dpaI0MBrs+vGcERB1ykLUYzzvBLFppgNs9J65X1sCqglFglk1qTaJKz7tKRW6gYe,iv:CVVqvh1C8jncf54+5p6Zd+2+HEyQrG2heZNVw/7S6+k=,tag:msVM3hE63wesrwgXrPQefw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-18T08:06:01Z"
    mac: ENC[AES256_GCM,data:q7WQHIHVKVflSL997SpJNikVtQyOi5Mt5sESwwbeYFULqOt+/D62wFyVrtXtKqyD1sdd/aOkbTPa3sLO34g+jP5TD+nmhIsxY7aH0Ju5bbuqQ0lg3Pc0YOhOiUHCSDYLdZHrGvoGJZV+rN7qDGkJ3DZ5kr75/4Tfw7lgjgXiF34=,iv:8WzaUGCbkFL9/GeqT3xNf0LrQvwiAXWV0XmLVVdK/94=,tag:b2wAdkj8AD6NA4ImqMu/9w==,type:str]
    pgp:
        - created_at: "2025-04-18T08:06:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+IztMpHMdavd3Ht3T/ORi7kP68mffW9hpF0FJxqvCSXhv
            0IwPd8QbHbkksnKvCMLkqO+4bWIC9A9QNmXCXtEY9/FfsU8Z2Bs1i+Di4AMfugU+
            kIWUJi64c3o+7e5Ue3SyDosNSbkQ5FIL3V/BU87tD+HcLaEPcZUhdQGHBIqXr/Zu
            wOeGeaG1iODh+8FiQrE80xLFXP0c3RIcEV+KokDIAE77xYiYEovfzQ4gtexCdTGG
            H8DXdCweNFtQDetVvIvuS5kenb3jABjzITQyCJ9Iapko+NwMj1yVw2FnLspb73L4
            nagnrvx6GsOamBp3bKlq+tqPD9X3UBQgwKParS+PCueuInNQn/LIdT/v8K6U0lqZ
            8Wa7qsQhmA85D4kltYA9CMKjvY9+a3ZHiOzN1H0bxBj/w0/qqUlh7xfaSo9k1Nux
            WWShJMM8Xo88hgLOcGqLdMxr2ta17neaOHJ6MRaVU5nH3vqSmsfSWGJ/rJY5N8W0
            NDTMK6SvVvopupR4DGZ1o7Kmbo2JgVeingRWab/GPDXvARkB+CAcFaQ/By5OcN/L
            SVmY1hb7hqDihBtZnY/pEhi9askDQvPExu3THZ0z8XIFdYKyYTU64vJ9ezX5JYqP
            v5eK7csGerYHyFNHvL8XAd1K7Vr02NDroVaBxLNgdY0mzS6Mrky9U1957l2L6mPS
            XAF8Fb256gnVFYBpfrqWPpdjsD5lILf0PgDXlqebnwJ5Mj9nwJS0Pjp4JRfXLTAc
            KVr3eY3+t2kITSEvdjIrKILFNTi8UY4O2SbqiiJ7Jf6SpQOyCy9one7c+1ZC
            =CwK5
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(url|username|password|id|secret|uri|key.+|host)$
    version: 3.9.3
