spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:LM1Gw2xHV5AE7wEqR1JNDOTnVdAGl+LhAVKfSL5TvNj8Id5pIBNeovubiz8gvP5nLWU=,iv:ebx1oXDuEYMkSzDV2VG5BPKIGgwQ70nlS+8f28gJgYM=,tag:iakNdom+CYDcOu1l+BvmWQ==,type:str]
        username: ENC[AES256_GCM,data:132gFyBc,iv:r81lu3K85p/pJeO3hwo/YroATyRwZXnK0X64tp4vRTY=,tag:T/+Xp4GHZjcNjzEQpGtwjQ==,type:str]
        password: ENC[AES256_GCM,data:odbiakJZ1qGJt5Q=,iv:+WC3fcXm57+4kOcFoBGHmA+PxzqYS/NPHqJt7qSjyhM=,tag:oRaRGsbPLAdwMOd1RVK75Q==,type:str]
    jpa:
        hibernate:
            ddl-auto: update
    data:
        redis:
            host: redis.phanescloud.com
            password: ENC[AES256_GCM,data:4KJVsK24IDMCzGI=,iv:dS/yhFvm/4N6m+tEWnA2DOX3lhbprlal/P63rWnJGe8=,tag:E1NVpATGsW85t0Taz7d1sg==,type:str]
server:
    servlet:
        session:
            timeout: 30m
            cookie:
                name: JSESSIONID
                http-only: true
                secure: true
frontend:
    url: ENC[AES256_GCM,data:gi5ju6uQQ26pIy8X88sFXOxlGa1s,iv:M8NRqcexRY1YKjfgygnz+zGcnOMctynAv3hQrzyvkkk=,tag:FSTHfbvJcuQom6mFynWu9g==,type:str]
naver:
    client:
        id: ENC[AES256_GCM,data:Ssj9lTs8wuDDNRpo3zzpiExMnY0=,iv:ctmvWcmGO32Fofz+qFzGKv6LJHjbQyOAMY4Xe1gOPdY=,tag:KH3vq/owiaO8Y9HM11hv4w==,type:str]
        secret: ENC[AES256_GCM,data:hL2m61V5XyHB1Q==,iv:L6cuCAkOwDsHvBYdFGY7M4FWfvwL8Rmecb0MT3ilxJM=,tag:fq+qGw62zZBQ/YfSrWqMPQ==,type:str]
    redirect:
        uri: ENC[AES256_GCM,data:TCwTkxLOc0XFJapOaqPXZwiIVmRz7hSI7tBXwE7hCG/edTcDzNV0Rs/8F0UJves2d4uXk7Cf4qBh,iv:F9oYxGPpHK7avfjO29PUkRAhBSda76c0ImV84gzazu4=,tag:+VnxwmD9OPU5Z6ie0gYkdA==,type:str]
google:
    client:
        id: ENC[AES256_GCM,data:hegMrqb+D6MUVb6ofdEuPau4AtdbOQsx0n+SVgd1+pYaHtKuEXbjAsel1jx80D2D3rBfqmPVGq6KAqrOkjW2cZmdSaekjmav,iv:XoyoslyekXtS6iYC3uK14vCnZcMeE9IkWlfmo33v178=,tag:0P/SO4PYf8p4cnMhcNMTuQ==,type:str]
        secret: ENC[AES256_GCM,data:JeWZO6i51zXYFgFVKCaKdPtrYwXCGKQijPWwA4kaiHM/NYI=,iv:ayLpS3xEDlcDbBZ5Lfkd40AzOYAQsSNMAAmZweUvcQA=,tag:Iy/JnalOodaSJBjeePSUJw==,type:str]
    redirect:
        uri: ENC[AES256_GCM,data:FqzxijfHu/8vQVX6EmHXZHg15RXtvxJNLnqknKWjf607WpBJp+mIWv8okjVC7q8lCRG2hmhlfeOd1A==,iv:jd3R06F/zA+PHtPJehZoqRcl5FEZRfRWutR34PyLenk=,tag:A+yHvVjtrtHgrcGgxXszMA==,type:str]
kakao:
    client:
        id: ENC[AES256_GCM,data:4jDqANIFuSc/YUkrLczGfn1ZxU8OfV1C+iSDYYoT+oY=,iv:LBKkjb1QWoyyiOLufX6cNf6a9FAPa2CSsttCvU1ks+0=,tag:PCoZkDxOSmPzfzu2/99ryA==,type:str]
        secret: ENC[AES256_GCM,data:EX/Spw+EW2JHPPsr6uWN2Yp+stnyJDzerFAYwoSPbiM=,iv:bV68UZSSZKx7YTfvbaoogBGfybpQij7ZyXi1lQSXnBc=,tag:E8FmS6iFhEMN6XuFlkK86w==,type:str]
    redirect:
        uri: ENC[AES256_GCM,data:jzHiXhGNe3mcMqFBDr5D/F3yedViuhvlNC2V9iL177MlCMte8u2vI/RwU0eSghOkQeyUUuemr/Iq,iv:4h64HhL5XOsmE7N0nQRHYTRKmNoVmUS5zYwC348YuLA=,tag:XecYZ5/c5uKO+W8nPVNZUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-14T11:56:25Z"
    mac: ENC[AES256_GCM,data:kPZU+yG+mDOAV2moeCFEJ03jta1kLSgDA0Hk6fFpHQmzDWvKxbW54/9Le5TuvbTRIw14SJfHjCygBliSfdv0L3DZIHo7YYk+PdU0ETfZB+sS+cmaURXz9PRwYcKyJpnR+BEmzObpDaF6WjaIujcqUDpCztNPJkAVX5W7iSCtR4c=,iv:gBf5fY+HoHD+SgiLXXi1TTfcV37CUb5elGYIhX6o79g=,tag:R2rhZf69Qj24Uba5Zd4Czg==,type:str]
    pgp:
        - created_at: "2025-04-14T11:56:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAkE0wFOWqhn4lddvsUncaidNSt1DTgqWACpu2HKkfQmyq
            MTUhjJXqsLLj6J7EEgCLPjFJ2sFL9McTWP/cWJ4aRebMwzvAUsMRBGErmC559nLw
            vOJojctQqhPgEDQc9xWP5GgJjuWkfer8E+OV/ksBR50narGNUyqL4khsAqCDp86g
            K+VCJRbmxbN024huKF1xeG4b0bhSunropGjNCwpbniJzihbY8oT0EV1FmbmMa89C
            rsLcUvIVDFqLpjaPYrtmmKcWNpIpk2a+oCzO2GL3WDDcSEW0fKGLA6mwll4LlGE+
            xbYBBCdicZDloiTiiiobPZBbQ7QvfWEQmHgcXyp812lheKPsJgvO55dk+25/oZJb
            MLOuytAJst3yPa6Cs+Sp7fCDQk99siS4EeuMpP4hyzCb3AX9p/Os4P9LS5FHKjbn
            +4u7wy8uJFmLLNmfSvBMQmy4iermuMMgxT5kQyvukhyESQVB24DB2Ma9XvfJSU6Y
            kzr07sJW/eZ9OiiK1aLY+h4sehSYeNuZmwWl0b8/TVZFVDtUoI8amlDFAsM9kB4X
            NGcNdkVi3dyCbYwSpAOLJepQwUFYIsp20zzjqJDjQ1MqTg9BWT/KXQjuThdeVmR+
            vEaZ2uax7WD2+DZtDqt9PXpkmIIouA6mgTe/B5HG9NXEDFjt3qQFrUndhkwvZ2zS
            XgEA0e2V9EebzeWVDaemMtsrJLnSxkFon/PkZWhL1JUywbn++0NUMIaNHXajFm3C
            HmRXe5DFzsgw5iS44qDda4BVOUCCyH9erhrtyTY4b+ss1ib8aMuxu+KBWMELntc=
            =HvA0
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(url|username|password|id|secret|uri)$
    version: 3.9.3
