server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:h6Y2BGJw7DKz7/C5isj9HoCsdg==,iv:hmSzqeCqWe9jrKJMGXvzDinL/k63d1a8zAwzEjSlL1k=,tag:s1JgfKm54I5PwRrrWu+QcQ==,type:str]
        key-store-password: ENC[AES256_GCM,data:fqShmqP/YqzGlTI=,iv:UMW6FvIztq6hLwQX2+XSe8X7lJEnKYC4TIA/mK0ugsk=,tag:xnpQCT/LefVGMl7t6MD7fg==,type:str]
        key-store-type: ENC[AES256_GCM,data:Jj9Tk36/,iv:56aWmY0ZPSzYxMpvFSjtW9zGd25o2zrWR5pmk8pF+N0=,tag:yIjNAvZq7RC44fzvA93laA==,type:str]
        key-alias: ENC[AES256_GCM,data:KyGdpmRK7WdMrQ==,iv:0iHGdFN+JnafKNuDc5Pek1ZpzAlVP1fFifrEJLdi1A8=,tag:rS8PsLzsAu+ZQOO7grAmnA==,type:str]
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:Ze+OgT0BC8cSR6+NQuIr/tg0kYyQGCbtFmpyfiuiicXOIJLUEehEg5XI7w6LSKp4gA==,iv:UWTy2gge+xPKlzeNEGKE2KNa6xzJlG59v10zxV/eTfc=,tag:LsojrKyO7UbUeyaU/UPpiQ==,type:str]
        username: ENC[AES256_GCM,data:jHfrqBxP,iv:lbwoFHZJySfO6UhsZBBysNnJ3CJ8p02SjpOJVXScAqo=,tag:3/K9N78he6d9cjJGtfCvPg==,type:str]
        password: ENC[AES256_GCM,data:18FGTrrJsFUJiGw=,iv:c7pCXATsEV9fpWA8+VC9cgz7eniF+pjHF5fyft/HncA=,tag:3hKNa2OGRhb6+evRwRgEuw==,type:str]
    data:
        redis:
            host: ENC[AES256_GCM,data:qRYESqtMZTsv8rAfMYJ584aWvlpr,iv:yf+NMVSlCeC6aeB/EYzX0yE3+TOFm5RCCzYila6SsHo=,tag:31Ic+wWBbaUTkOZODfl+ww==,type:str]
            password: ENC[AES256_GCM,data:+HDy+CqavND79JY=,iv:+r1UadnLMIrBhCvCVdqW9GdXs5b+9fZQJ+eZFMuStyc=,tag:uEeMpDiYyPigpnNbu0FVkw==,type:str]
    jpa:
        hibernate:
            ddl-auto: create
app:
    domain:
        frontend: ENC[AES256_GCM,data:bFWzwSXj1inz6HuXw7+ykJmKrYEC9Trq9wNA,iv:SFeRVPBH/7YyURD3t1/pZcZM9LuPGhyQSIJRe7HR/Y8=,tag:TftjQ34PnahmBakf8mu0MA==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:oqnOMMK23M/VTMgPGfrv6LwOMZIr5ws9STfjhri9cqIzRSUC/mXEd9blRop2TKn6vKNJmNxd,iv:GthUEwyJqC9CCejJwI9bZs/vrcKHIy/zkyQlv/zClmM=,tag:/3GaeXVFyOQ/JimIw71F3Q==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:OhI6fvXWb7hsnzP5M2avMgILTMZBl0vMgeFh0YrMwcKqDwWDK/MgBCIgcepMKv31LdZ/FpQgMg==,iv:zP4IGcKMaHEsqpc1VtL2uNKjam5Nk/qgSK1AKpMWkSI=,tag:9G+QF5Rj58+mRhgLRnAPaw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:fdHxRwwcJVoczFfo+/GNxXYt0GPgcz3gHC3wnIR16oai88wgacqY4BGvnbxTNyhzpcC41efc,iv:5ro/hLo/E+H/K9K5avFJ+e5SkNmy1WfiLlEmWSyIfTU=,tag:jxtnumZzlMywPQqrxf/jQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-21T09:18:13Z"
    mac: ENC[AES256_GCM,data:vTZIshBwwdilVQG6/+bNXeif2agO8cgMu8BXcvFzR023/cHiEpp8KUHeWdW4cs9np3gXtYw7fWWDOWvI8p9M7wEsi4df0/t5Mtt7D/5+GtkdQOdhZH7BVkjDCFpVuFV3r01q9bC95iSqHkUouKy0CXwG6o+hFjM5dbw1HOPmJxE=,iv:B2R6+55jC2qvyPItfmHmtbMwGwwBqnJYVMT4GhpvAmc=,tag:xyIJ9nFNIs19sfhXtSb8wQ==,type:str]
    pgp:
        - created_at: "2025-04-21T09:18:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+PudnPc88SBitUP5tvSgBuyDAG/JhlywGvcmF1GDnXsY7
            l+xrijmmsB1+sl6l8AqF2P0nGLVbR9sC4F9k630FowsKxyHzhO+PxRtt9kP6te9s
            4NuvhshxzBw87LhWTvbP6WJ1HgJLIgy52cOTalxnt+6qVYQDfvjWavrHvxHdk7xn
            AqEuFwZ6iJh/elIvfMLG5vb/y6GHaieCRumrYMkvrRd0rNP/DqQvpgrrl4elVJ8N
            WbiAs78snmn8+HGD4Ui+vIfQI8vgLshQdjPSKEfZW/GplApg2JFlcO7A+YJeEnHF
            M77X8Q2QpImjJgc2LaKlPAPoJRxr28Nrx7oSEguM6lGw/rTdPca1ZeUXDNxsZXxc
            45DmOoyAxjTU6/f9Cs+2Iz/X++21pRDETnyM/LksBvBYgIy0LEYyjFsMM7ShbHl7
            eP/jZ+/EWcfAJHWXOb5k3ZCXms1Rnn9AfescUw+pE2IWrbmrQEUHoplnU8k01UxA
            sCamO67P91wMZExatuGxoPIxEJqv101nG2Vad013VDkVG7nbh/ZHlKyLJfLVvBF2
            CLD50Uh01Kf8089whL6gc1FnWYGzPIP7yTrSsByYFdWHwFolxtNBQxfNCz2phWXA
            stN3fHEIlNBIGYMXk3x9gUyDxcMkBGorkg5BK2tb0UnBCuUBQtnCHFPiKqKZvyPS
            XgFkP5cTt53cY35dVbqf+DzKA3EGj3a8IZwR26fhnSxlXqcRpev7yjuVjYwEPuAy
            kIOuIa10FurWCzV26695Dvxzyt6YzMo+SJK4ikjb/IZQsZe3QpQz/BmYKd1mJLA=
            =Njyv
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
